name: findscent
description: "AI-Driven Perfume Recommendation App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  csv: ^6.0.0
  
  # Veritabanı ve State Management paketlerini buraya ekledik:
  sqflite: ^2.3.0
  path: ^1.9.0
  provider: ^6.1.1
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # CSV veya hazır DB dosyanı ekleyeceğin yer burası olacak:
  assets:
    - assets/final_cleaned_perfumes.csv